"""initial_schema

Revision ID: 17dbf7118f92
Revises: 
Create Date: 2026-05-27 23:28:12.246496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17dbf7118f92'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_calls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('service', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidates',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('file_name', sa.String(length=512), nullable=True),
    sa.Column('structured_info', sa.Text(), nullable=True),
    sa.Column('cv_text', sa.Text(), nullable=True),
    sa.Column('skills_text', sa.Text(), nullable=True),
    sa.Column('experience_text', sa.Text(), nullable=True),
    sa.Column('certifications_text', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_sessions',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('candidate_name', sa.String(length=256), nullable=False),
    sa.Column('candidate_email', sa.String(length=256), nullable=False),
    sa.Column('job_title', sa.String(length=256), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('interview_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('candidate_name', sa.String(length=256), nullable=False),
    sa.Column('candidate_email', sa.String(length=256), nullable=False),
    sa.Column('job_title', sa.String(length=256), nullable=False),
    sa.Column('questions_json', sa.Text(), nullable=False),
    sa.Column('answers_json', sa.Text(), nullable=False),
    sa.Column('scores_json', sa.Text(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('red_flags', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.String(length=64), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['token'], ['interview_sessions.token'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interview_results')
    op.drop_table('interview_sessions')
    op.drop_table('candidates')
    op.drop_table('ai_calls')
    # ### end Alembic commands ###
